import { MLSTeam, MLSPlayer } from './types';

export const MLS_TEAMS: MLSTeam[] = [
  {
    id: 'inter-miami',
    name: 'Inter Miami CF',
    shortName: 'Inter Miami',
    abbreviation: 'MIA',
    city: 'Fort Lauderdale',
    conference: 'Eastern',
    primaryColor: '#F7B5CD',
    secondaryColor: '#000000',
    stadium: 'Chase Stadium',
    stadiumCapacity: 21550,
    foundedYear: 2018,
    estimatedRevenue: 95_000_000,
    estimatedMarketValue: 900_000_000,
    standingsPoints: 74,
    wins: 22,
    losses: 8,
    draws: 8,
    goalsFor: 75,
    goalsAgainst: 49,
    leaguePosition: 1,
    season: '2024',
  },
  {
    id: 'la-galaxy',
    name: 'LA Galaxy',
    shortName: 'LA Galaxy',
    abbreviation: 'LAG',
    city: 'Carson',
    conference: 'Western',
    primaryColor: '#00245D',
    secondaryColor: '#FFD700',
    stadium: 'Dignity Health Sports Park',
    stadiumCapacity: 27000,
    foundedYear: 1996,
    estimatedRevenue: 72_000_000,
    estimatedMarketValue: 480_000_000,
    standingsPoints: 58,
    wins: 16,
    losses: 12,
    draws: 10,
    goalsFor: 60,
    goalsAgainst: 52,
    leaguePosition: 4,
    season: '2024',
  },
  {
    id: 'lafc',
    name: 'LAFC',
    shortName: 'LAFC',
    abbreviation: 'LAFC',
    city: 'Los Angeles',
    conference: 'Western',
    primaryColor: '#000000',
    secondaryColor: '#C39E6D',
    stadium: 'BMO Stadium',
    stadiumCapacity: 22000,
    foundedYear: 2018,
    estimatedRevenue: 78_000_000,
    estimatedMarketValue: 600_000_000,
    standingsPoints: 63,
    wins: 18,
    losses: 12,
    draws: 8,
    goalsFor: 64,
    goalsAgainst: 48,
    leaguePosition: 2,
    season: '2024',
  },
  {
    id: 'seattle-sounders',
    name: 'Seattle Sounders FC',
    shortName: 'Seattle Sounders',
    abbreviation: 'SEA',
    city: 'Seattle',
    conference: 'Western',
    primaryColor: '#5D9741',
    secondaryColor: '#003087',
    stadium: 'Lumen Field',
    stadiumCapacity: 37722,
    foundedYear: 2009,
    estimatedRevenue: 65_000_000,
    estimatedMarketValue: 420_000_000,
    standingsPoints: 55,
    wins: 15,
    losses: 14,
    draws: 9,
    goalsFor: 56,
    goalsAgainst: 54,
    leaguePosition: 5,
    season: '2024',
  },
  {
    id: 'atlanta-united',
    name: 'Atlanta United FC',
    shortName: 'Atlanta United',
    abbreviation: 'ATL',
    city: 'Atlanta',
    conference: 'Eastern',
    primaryColor: '#80000A',
    secondaryColor: '#A19060',
    stadium: 'Mercedes-Benz Stadium',
    stadiumCapacity: 71000,
    foundedYear: 2017,
    estimatedRevenue: 68_000_000,
    estimatedMarketValue: 510_000_000,
    standingsPoints: 52,
    wins: 14,
    losses: 14,
    draws: 10,
    goalsFor: 58,
    goalsAgainst: 59,
    leaguePosition: 5,
    season: '2024',
  },
  {
    id: 'portland-timbers',
    name: 'Portland Timbers',
    shortName: 'Portland Timbers',
    abbreviation: 'POR',
    city: 'Portland',
    conference: 'Western',
    primaryColor: '#004812',
    secondaryColor: '#EBE72B',
    stadium: 'Providence Park',
    stadiumCapacity: 25218,
    foundedYear: 2011,
    estimatedRevenue: 55_000_000,
    estimatedMarketValue: 350_000_000,
    standingsPoints: 50,
    wins: 13,
    losses: 14,
    draws: 11,
    goalsFor: 55,
    goalsAgainst: 58,
    leaguePosition: 7,
    season: '2024',
  },
  {
    id: 'fc-cincinnati',
    name: 'FC Cincinnati',
    shortName: 'FC Cincinnati',
    abbreviation: 'CIN',
    city: 'Cincinnati',
    conference: 'Eastern',
    primaryColor: '#003087',
    secondaryColor: '#FE5000',
    stadium: 'TQL Stadium',
    stadiumCapacity: 26000,
    foundedYear: 2019,
    estimatedRevenue: 58_000_000,
    estimatedMarketValue: 380_000_000,
    standingsPoints: 65,
    wins: 19,
    losses: 10,
    draws: 9,
    goalsFor: 68,
    goalsAgainst: 52,
    leaguePosition: 2,
    season: '2024',
  },
  {
    id: 'columbus-crew',
    name: 'Columbus Crew',
    shortName: 'Columbus Crew',
    abbreviation: 'CLB',
    city: 'Columbus',
    conference: 'Eastern',
    primaryColor: '#FEDA00',
    secondaryColor: '#000000',
    stadium: 'Lower.com Field',
    stadiumCapacity: 20371,
    foundedYear: 1996,
    estimatedRevenue: 52_000_000,
    estimatedMarketValue: 310_000_000,
    standingsPoints: 58,
    wins: 16,
    losses: 12,
    draws: 10,
    goalsFor: 62,
    goalsAgainst: 55,
    leaguePosition: 3,
    season: '2024',
  },
];

export const MLS_PLAYERS: MLSPlayer[] = [
  // ─── INTER MIAMI ────────────────────────────────────────────────
  {
    id: 'messi',
    name: 'Lionel Messi',
    teamId: 'inter-miami',
    position: 'ST',
    nationality: 'Argentinian',
    age: 37,
    guaranteedComp: 20_446_667,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 19, gamesStarted: 18, minutesPlayed: 1540, goals: 11, assists: 14, xG: 9.8, xA: 11.2, keyPasses: 87, dribbles: 43, tackles: 12, interceptions: 8, passAccuracy: 87, shots: 54, shotsOnTarget: 28 },
  },
  {
    id: 'busquets',
    name: 'Sergio Busquets',
    teamId: 'inter-miami',
    position: 'CM',
    nationality: 'Spanish',
    age: 36,
    guaranteedComp: 7_800_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 27, minutesPlayed: 2340, goals: 1, assists: 5, xG: 0.8, xA: 4.1, keyPasses: 62, dribbles: 18, tackles: 45, interceptions: 38, passAccuracy: 91, shots: 12, shotsOnTarget: 5 },
  },
  {
    id: 'jordi-alba',
    name: 'Jordi Alba',
    teamId: 'inter-miami',
    position: 'LB',
    nationality: 'Spanish',
    age: 35,
    guaranteedComp: 3_500_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 25, minutesPlayed: 2150, goals: 2, assists: 10, xG: 1.2, xA: 8.3, keyPasses: 71, dribbles: 34, tackles: 38, interceptions: 22, passAccuracy: 88, shots: 18, shotsOnTarget: 8 },
  },
  {
    id: 'suarez',
    name: 'Luis Suárez',
    teamId: 'inter-miami',
    position: 'ST',
    nationality: 'Uruguayan',
    age: 37,
    guaranteedComp: 3_500_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 25, gamesStarted: 22, minutesPlayed: 1880, goals: 14, assists: 5, xG: 12.1, xA: 4.8, keyPasses: 41, dribbles: 28, tackles: 5, interceptions: 3, passAccuracy: 76, shots: 68, shotsOnTarget: 34 },
  },
  {
    id: 'callender',
    name: 'Drake Callender',
    teamId: 'inter-miami',
    position: 'GK',
    nationality: 'American',
    age: 27,
    guaranteedComp: 450_000,
    budgetCharge: 450_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 34, gamesStarted: 34, minutesPlayed: 3060, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 68, shots: 0, shotsOnTarget: 0 },
  },
  {
    id: 'yedlin',
    name: 'DeAndre Yedlin',
    teamId: 'inter-miami',
    position: 'RB',
    nationality: 'American',
    age: 31,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 29, gamesStarted: 27, minutesPlayed: 2340, goals: 1, assists: 3, xG: 0.6, xA: 2.4, keyPasses: 28, dribbles: 15, tackles: 41, interceptions: 30, passAccuracy: 82, shots: 8, shotsOnTarget: 3 },
  },
  {
    id: 'cremaschi',
    name: 'Benjamin Cremaschi',
    teamId: 'inter-miami',
    position: 'CM',
    nationality: 'American',
    age: 20,
    guaranteedComp: 350_000,
    budgetCharge: 350_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 26, minutesPlayed: 2180, goals: 3, assists: 6, xG: 2.8, xA: 5.1, keyPasses: 55, dribbles: 42, tackles: 38, interceptions: 25, passAccuracy: 84, shots: 25, shotsOnTarget: 12 },
  },
  {
    id: 'gregore',
    name: 'Gregore',
    teamId: 'inter-miami',
    position: 'CDM',
    nationality: 'Brazilian',
    age: 29,
    guaranteedComp: 850_000,
    budgetCharge: 850_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 32, gamesStarted: 30, minutesPlayed: 2650, goals: 1, assists: 2, xG: 0.9, xA: 1.8, keyPasses: 31, dribbles: 12, tackles: 78, interceptions: 55, passAccuracy: 86, shots: 10, shotsOnTarget: 4 },
  },
  {
    id: 'farias',
    name: 'Facundo Farías',
    teamId: 'inter-miami',
    position: 'LW',
    nationality: 'Argentinian',
    age: 22,
    guaranteedComp: 1_400_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 18, minutesPlayed: 1520, goals: 5, assists: 4, xG: 4.2, xA: 3.6, keyPasses: 44, dribbles: 51, tackles: 18, interceptions: 12, passAccuracy: 79, shots: 32, shotsOnTarget: 14 },
  },
  {
    id: 'rojas',
    name: 'Matías Rojas',
    teamId: 'inter-miami',
    position: 'CAM',
    nationality: 'Paraguayan',
    age: 28,
    guaranteedComp: 1_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 20, minutesPlayed: 1740, goals: 4, assists: 7, xG: 3.5, xA: 6.2, keyPasses: 58, dribbles: 38, tackles: 22, interceptions: 14, passAccuracy: 83, shots: 28, shotsOnTarget: 13 },
  },
  {
    id: 'freire',
    name: 'Nicolás Freire',
    teamId: 'inter-miami',
    position: 'CB',
    nationality: 'Argentinian',
    age: 29,
    guaranteedComp: 250_000,
    budgetCharge: 250_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2280, goals: 2, assists: 0, xG: 1.4, xA: 0.3, keyPasses: 12, dribbles: 5, tackles: 52, interceptions: 44, passAccuracy: 85, shots: 6, shotsOnTarget: 2 },
  },
  {
    id: 'gonzalez-pirez',
    name: 'Leandro González Pirez',
    teamId: 'inter-miami',
    position: 'CB',
    nationality: 'Argentinian',
    age: 32,
    guaranteedComp: 350_000,
    budgetCharge: 350_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 24, minutesPlayed: 2100, goals: 1, assists: 1, xG: 0.8, xA: 0.8, keyPasses: 14, dribbles: 3, tackles: 48, interceptions: 40, passAccuracy: 84, shots: 5, shotsOnTarget: 2 },
  },
  {
    id: 'noah-allen',
    name: 'Noah Allen',
    teamId: 'inter-miami',
    position: 'LB',
    nationality: 'American',
    age: 23,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 14, minutesPlayed: 1240, goals: 0, assists: 2, xG: 0.3, xA: 1.6, keyPasses: 18, dribbles: 10, tackles: 28, interceptions: 18, passAccuracy: 80, shots: 4, shotsOnTarget: 1 },
  },
  {
    id: 'robert-taylor',
    name: 'Robert Taylor',
    teamId: 'inter-miami',
    position: 'RW',
    nationality: 'Finnish',
    age: 30,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 18, gamesStarted: 10, minutesPlayed: 840, goals: 2, assists: 1, xG: 1.8, xA: 0.9, keyPasses: 22, dribbles: 28, tackles: 8, interceptions: 5, passAccuracy: 77, shots: 18, shotsOnTarget: 7 },
  },
  {
    id: 'robbie-robinson',
    name: 'Robbie Robinson',
    teamId: 'inter-miami',
    position: 'ST',
    nationality: 'American',
    age: 25,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 8, minutesPlayed: 720, goals: 4, assists: 1, xG: 3.6, xA: 0.8, keyPasses: 16, dribbles: 20, tackles: 4, interceptions: 2, passAccuracy: 72, shots: 28, shotsOnTarget: 13 },
  },

  // ─── LA GALAXY ──────────────────────────────────────────────────
  {
    id: 'riqui-puig',
    name: 'Riqui Puig',
    teamId: 'la-galaxy',
    position: 'CAM',
    nationality: 'Spanish',
    age: 25,
    guaranteedComp: 4_000_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2460, goals: 8, assists: 14, xG: 7.2, xA: 11.8, keyPasses: 94, dribbles: 88, tackles: 28, interceptions: 18, passAccuracy: 85, shots: 48, shotsOnTarget: 22 },
  },
  {
    id: 'paintsil',
    name: 'Joseph Paintsil',
    teamId: 'la-galaxy',
    position: 'RW',
    nationality: 'Ghanaian',
    age: 24,
    guaranteedComp: 1_800_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 32, gamesStarted: 30, minutesPlayed: 2620, goals: 14, assists: 6, xG: 11.8, xA: 5.2, keyPasses: 52, dribbles: 96, tackles: 18, interceptions: 12, passAccuracy: 74, shots: 88, shotsOnTarget: 42 },
  },
  {
    id: 'gabriel-pec',
    name: 'Gabriel Pec',
    teamId: 'la-galaxy',
    position: 'LW',
    nationality: 'Brazilian',
    age: 23,
    guaranteedComp: 2_000_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 31, gamesStarted: 29, minutesPlayed: 2540, goals: 12, assists: 8, xG: 10.2, xA: 6.8, keyPasses: 64, dribbles: 78, tackles: 22, interceptions: 14, passAccuracy: 78, shots: 76, shotsOnTarget: 36 },
  },
  {
    id: 'john-nelson',
    name: 'John Nelson',
    teamId: 'la-galaxy',
    position: 'RB',
    nationality: 'American',
    age: 24,
    guaranteedComp: 450_000,
    budgetCharge: 450_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 25, minutesPlayed: 2180, goals: 1, assists: 3, xG: 0.7, xA: 2.4, keyPasses: 24, dribbles: 12, tackles: 48, interceptions: 36, passAccuracy: 83, shots: 7, shotsOnTarget: 2 },
  },
  {
    id: 'brugman',
    name: 'Gastón Brugman',
    teamId: 'la-galaxy',
    position: 'CDM',
    nationality: 'Uruguayan',
    age: 32,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 2, assists: 4, xG: 1.6, xA: 3.2, keyPasses: 42, dribbles: 22, tackles: 64, interceptions: 48, passAccuracy: 87, shots: 18, shotsOnTarget: 7 },
  },
  {
    id: 'cerrillo',
    name: 'Edwin Cerrillo',
    teamId: 'la-galaxy',
    position: 'CM',
    nationality: 'American',
    age: 25,
    guaranteedComp: 900_000,
    budgetCharge: 900_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 31, gamesStarted: 28, minutesPlayed: 2380, goals: 3, assists: 5, xG: 2.8, xA: 4.2, keyPasses: 48, dribbles: 35, tackles: 52, interceptions: 34, passAccuracy: 84, shots: 24, shotsOnTarget: 10 },
  },
  {
    id: 'joveljic',
    name: 'Dejan Joveljić',
    teamId: 'la-galaxy',
    position: 'ST',
    nationality: 'Serbian',
    age: 23,
    guaranteedComp: 1_400_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 29, gamesStarted: 24, minutesPlayed: 2080, goals: 11, assists: 4, xG: 9.8, xA: 3.4, keyPasses: 32, dribbles: 34, tackles: 8, interceptions: 4, passAccuracy: 74, shots: 62, shotsOnTarget: 28 },
  },
  {
    id: 'john-tolkin',
    name: 'John Tolkin',
    teamId: 'la-galaxy',
    position: 'LB',
    nationality: 'American',
    age: 22,
    guaranteedComp: 350_000,
    budgetCharge: 350_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 22, minutesPlayed: 1880, goals: 0, assists: 4, xG: 0.4, xA: 3.2, keyPasses: 22, dribbles: 18, tackles: 38, interceptions: 24, passAccuracy: 82, shots: 5, shotsOnTarget: 1 },
  },
  {
    id: 'miki-yamane',
    name: 'Miki Yamane',
    teamId: 'la-galaxy',
    position: 'RB',
    nationality: 'Japanese',
    age: 29,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 18, minutesPlayed: 1560, goals: 2, assists: 2, xG: 1.4, xA: 1.8, keyPasses: 26, dribbles: 14, tackles: 34, interceptions: 26, passAccuracy: 84, shots: 10, shotsOnTarget: 4 },
  },
  {
    id: 'mark-delgado',
    name: 'Mark Delgado',
    teamId: 'la-galaxy',
    position: 'CM',
    nationality: 'American',
    age: 31,
    guaranteedComp: 400_000,
    budgetCharge: 400_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 18, minutesPlayed: 1560, goals: 1, assists: 3, xG: 0.9, xA: 2.4, keyPasses: 36, dribbles: 15, tackles: 42, interceptions: 28, passAccuracy: 85, shots: 12, shotsOnTarget: 4 },
  },
  {
    id: 'fagundez',
    name: 'Diego Fagúndez',
    teamId: 'la-galaxy',
    position: 'LM',
    nationality: 'Uruguayan',
    age: 29,
    guaranteedComp: 800_000,
    budgetCharge: 800_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 22, minutesPlayed: 1940, goals: 5, assists: 6, xG: 4.4, xA: 5.1, keyPasses: 48, dribbles: 44, tackles: 14, interceptions: 10, passAccuracy: 79, shots: 42, shotsOnTarget: 18 },
  },
  {
    id: 'jonathan-perez',
    name: 'Jonathan Pérez',
    teamId: 'la-galaxy',
    position: 'CB',
    nationality: 'Costa Rican',
    age: 24,
    guaranteedComp: 200_000,
    budgetCharge: 200_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 16, minutesPlayed: 1380, goals: 1, assists: 0, xG: 0.8, xA: 0.2, keyPasses: 8, dribbles: 3, tackles: 38, interceptions: 28, passAccuracy: 82, shots: 4, shotsOnTarget: 1 },
  },
  {
    id: 'kevin-cabral',
    name: 'Kevin Cabral',
    teamId: 'la-galaxy',
    position: 'ST',
    nationality: 'French',
    age: 25,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 18, gamesStarted: 10, minutesPlayed: 820, goals: 4, assists: 1, xG: 3.6, xA: 0.9, keyPasses: 14, dribbles: 18, tackles: 4, interceptions: 3, passAccuracy: 70, shots: 24, shotsOnTarget: 10 },
  },
  {
    id: 'jonathan-bond',
    name: 'Jonathan Bond',
    teamId: 'la-galaxy',
    position: 'GK',
    nationality: 'English',
    age: 31,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 34, gamesStarted: 34, minutesPlayed: 3060, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 65, shots: 0, shotsOnTarget: 0 },
  },

  // ─── LAFC ────────────────────────────────────────────────────────
  {
    id: 'bouanga',
    name: 'Denis Bouanga',
    teamId: 'lafc',
    position: 'LW',
    nationality: 'Gabonese',
    age: 29,
    guaranteedComp: 2_800_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 33, gamesStarted: 32, minutesPlayed: 2820, goals: 18, assists: 7, xG: 15.8, xA: 6.2, keyPasses: 58, dribbles: 84, tackles: 22, interceptions: 14, passAccuracy: 76, shots: 102, shotsOnTarget: 48 },
  },
  {
    id: 'giroud',
    name: 'Olivier Giroud',
    teamId: 'lafc',
    position: 'ST',
    nationality: 'French',
    age: 38,
    guaranteedComp: 3_500_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 24, minutesPlayed: 2080, goals: 13, assists: 4, xG: 11.4, xA: 3.6, keyPasses: 28, dribbles: 12, tackles: 6, interceptions: 4, passAccuracy: 72, shots: 72, shotsOnTarget: 35 },
  },
  {
    id: 'lloris',
    name: 'Hugo Lloris',
    teamId: 'lafc',
    position: 'GK',
    nationality: 'French',
    age: 37,
    guaranteedComp: 3_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 30, minutesPlayed: 2700, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 70, shots: 0, shotsOnTarget: 0 },
  },
  {
    id: 'tillman',
    name: 'Timothy Tillman',
    teamId: 'lafc',
    position: 'CAM',
    nationality: 'American/German',
    age: 26,
    guaranteedComp: 1_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 29, gamesStarted: 26, minutesPlayed: 2280, goals: 6, assists: 9, xG: 5.2, xA: 7.8, keyPasses: 76, dribbles: 52, tackles: 28, interceptions: 18, passAccuracy: 84, shots: 38, shotsOnTarget: 16 },
  },
  {
    id: 'biuk',
    name: 'Stipe Biuk',
    teamId: 'lafc',
    position: 'RW',
    nationality: 'Croatian',
    age: 22,
    guaranteedComp: 900_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 22, minutesPlayed: 1840, goals: 5, assists: 6, xG: 4.4, xA: 5.2, keyPasses: 44, dribbles: 62, tackles: 14, interceptions: 10, passAccuracy: 75, shots: 48, shotsOnTarget: 20 },
  },
  {
    id: 'ilie-sanchez',
    name: 'Ilie Sánchez',
    teamId: 'lafc',
    position: 'CDM',
    nationality: 'Spanish',
    age: 30,
    guaranteedComp: 800_000,
    budgetCharge: 800_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 32, gamesStarted: 30, minutesPlayed: 2640, goals: 1, assists: 3, xG: 0.8, xA: 2.4, keyPasses: 38, dribbles: 18, tackles: 74, interceptions: 58, passAccuracy: 88, shots: 14, shotsOnTarget: 5 },
  },
  {
    id: 'aaron-long',
    name: 'Aaron Long',
    teamId: 'lafc',
    position: 'CB',
    nationality: 'American',
    age: 31,
    guaranteedComp: 1_100_000,
    budgetCharge: 1_100_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2460, goals: 2, assists: 1, xG: 1.6, xA: 0.9, keyPasses: 14, dribbles: 4, tackles: 58, interceptions: 48, passAccuracy: 86, shots: 8, shotsOnTarget: 3 },
  },
  {
    id: 'palacios',
    name: 'Diego Palacios',
    teamId: 'lafc',
    position: 'LB',
    nationality: 'Ecuadorian',
    age: 25,
    guaranteedComp: 800_000,
    budgetCharge: 800_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 1, assists: 4, xG: 0.8, xA: 3.2, keyPasses: 28, dribbles: 22, tackles: 44, interceptions: 32, passAccuracy: 82, shots: 8, shotsOnTarget: 3 },
  },
  {
    id: 'hollingshead',
    name: 'Ryan Hollingshead',
    teamId: 'lafc',
    position: 'LM',
    nationality: 'American',
    age: 32,
    guaranteedComp: 650_000,
    budgetCharge: 650_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 20, minutesPlayed: 1740, goals: 3, assists: 5, xG: 2.6, xA: 4.2, keyPasses: 34, dribbles: 28, tackles: 22, interceptions: 16, passAccuracy: 79, shots: 22, shotsOnTarget: 9 },
  },
  {
    id: 'chanot',
    name: 'Maxime Chanot',
    teamId: 'lafc',
    position: 'CB',
    nationality: 'Luxembourgish',
    age: 34,
    guaranteedComp: 1_000_000,
    budgetCharge: 1_000_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 24, minutesPlayed: 2100, goals: 2, assists: 1, xG: 1.4, xA: 0.8, keyPasses: 12, dribbles: 3, tackles: 48, interceptions: 40, passAccuracy: 85, shots: 8, shotsOnTarget: 3 },
  },
  {
    id: 'obrien',
    name: "Lewis O'Brien",
    teamId: 'lafc',
    position: 'CM',
    nationality: 'English',
    age: 25,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 18, minutesPlayed: 1560, goals: 2, assists: 4, xG: 1.8, xA: 3.4, keyPasses: 44, dribbles: 28, tackles: 38, interceptions: 24, passAccuracy: 83, shots: 18, shotsOnTarget: 7 },
  },
  {
    id: 'kwadwo-opoku',
    name: 'Kwadwo Opoku',
    teamId: 'lafc',
    position: 'RW',
    nationality: 'Ghanaian',
    age: 24,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 12, minutesPlayed: 1020, goals: 4, assists: 2, xG: 3.6, xA: 1.8, keyPasses: 28, dribbles: 48, tackles: 10, interceptions: 8, passAccuracy: 72, shots: 38, shotsOnTarget: 16 },
  },
  {
    id: 'cristian-tello',
    name: 'Cristian Tello',
    teamId: 'lafc',
    position: 'RM',
    nationality: 'Spanish',
    age: 33,
    guaranteedComp: 800_000,
    budgetCharge: 800_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 14, minutesPlayed: 1180, goals: 3, assists: 3, xG: 2.6, xA: 2.8, keyPasses: 32, dribbles: 34, tackles: 8, interceptions: 6, passAccuracy: 78, shots: 28, shotsOnTarget: 11 },
  },

  // ─── SEATTLE SOUNDERS ────────────────────────────────────────────
  {
    id: 'lodeiro',
    name: 'Nicolás Lodeiro',
    teamId: 'seattle-sounders',
    position: 'CAM',
    nationality: 'Uruguayan',
    age: 35,
    guaranteedComp: 2_800_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 22, minutesPlayed: 1880, goals: 3, assists: 9, xG: 2.8, xA: 8.2, keyPasses: 78, dribbles: 38, tackles: 24, interceptions: 16, passAccuracy: 86, shots: 26, shotsOnTarget: 10 },
  },
  {
    id: 'ruidiaz',
    name: 'Raúl Ruidíaz',
    teamId: 'seattle-sounders',
    position: 'ST',
    nationality: 'Peruvian',
    age: 33,
    guaranteedComp: 3_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 24, minutesPlayed: 2040, goals: 12, assists: 3, xG: 10.8, xA: 2.8, keyPasses: 22, dribbles: 24, tackles: 4, interceptions: 2, passAccuracy: 68, shots: 74, shotsOnTarget: 34 },
  },
  {
    id: 'rusnak',
    name: 'Albert Rusnák',
    teamId: 'seattle-sounders',
    position: 'CM',
    nationality: 'Slovak',
    age: 30,
    guaranteedComp: 1_100_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 6, assists: 8, xG: 5.4, xA: 7.2, keyPasses: 68, dribbles: 42, tackles: 32, interceptions: 22, passAccuracy: 84, shots: 44, shotsOnTarget: 18 },
  },
  {
    id: 'jordan-morris',
    name: 'Jordan Morris',
    teamId: 'seattle-sounders',
    position: 'LW',
    nationality: 'American',
    age: 29,
    guaranteedComp: 1_500_000,
    budgetCharge: 1_500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 32, gamesStarted: 30, minutesPlayed: 2620, goals: 10, assists: 6, xG: 9.2, xA: 5.4, keyPasses: 48, dribbles: 68, tackles: 18, interceptions: 14, passAccuracy: 77, shots: 68, shotsOnTarget: 30 },
  },
  {
    id: 'joao-paulo',
    name: 'João Paulo',
    teamId: 'seattle-sounders',
    position: 'CM',
    nationality: 'Brazilian',
    age: 30,
    guaranteedComp: 1_200_000,
    budgetCharge: 1_200_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2240, goals: 4, assists: 8, xG: 3.6, xA: 7.2, keyPasses: 64, dribbles: 38, tackles: 44, interceptions: 32, passAccuracy: 86, shots: 32, shotsOnTarget: 14 },
  },
  {
    id: 'cristian-roldan',
    name: 'Cristian Roldan',
    teamId: 'seattle-sounders',
    position: 'CM',
    nationality: 'American',
    age: 29,
    guaranteedComp: 850_000,
    budgetCharge: 850_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 26, minutesPlayed: 2280, goals: 3, assists: 5, xG: 2.6, xA: 4.4, keyPasses: 52, dribbles: 34, tackles: 48, interceptions: 34, passAccuracy: 84, shots: 28, shotsOnTarget: 11 },
  },
  {
    id: 'stefan-frei',
    name: 'Stefan Frei',
    teamId: 'seattle-sounders',
    position: 'GK',
    nationality: 'Swiss',
    age: 37,
    guaranteedComp: 900_000,
    budgetCharge: 900_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 32, gamesStarted: 32, minutesPlayed: 2880, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 67, shots: 0, shotsOnTarget: 0 },
  },
  {
    id: 'arreaga',
    name: 'Xavier Arreaga',
    teamId: 'seattle-sounders',
    position: 'CB',
    nationality: 'Ecuadorian',
    age: 28,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2460, goals: 2, assists: 1, xG: 1.4, xA: 0.9, keyPasses: 14, dribbles: 5, tackles: 52, interceptions: 42, passAccuracy: 84, shots: 8, shotsOnTarget: 3 },
  },
  {
    id: 'nouhou',
    name: 'Nouhou Tolo',
    teamId: 'seattle-sounders',
    position: 'LB',
    nationality: 'Cameroonian',
    age: 28,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 1, assists: 3, xG: 0.7, xA: 2.4, keyPasses: 24, dribbles: 16, tackles: 44, interceptions: 30, passAccuracy: 80, shots: 6, shotsOnTarget: 2 },
  },
  {
    id: 'jackson-ragen',
    name: 'Jackson Ragen',
    teamId: 'seattle-sounders',
    position: 'CB',
    nationality: 'American',
    age: 24,
    guaranteedComp: 400_000,
    budgetCharge: 400_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2260, goals: 1, assists: 0, xG: 0.8, xA: 0.3, keyPasses: 10, dribbles: 3, tackles: 50, interceptions: 40, passAccuracy: 83, shots: 5, shotsOnTarget: 2 },
  },
  {
    id: 'obed-vargas',
    name: 'Obed Vargas',
    teamId: 'seattle-sounders',
    position: 'CDM',
    nationality: 'American',
    age: 19,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 14, minutesPlayed: 1180, goals: 1, assists: 2, xG: 0.8, xA: 1.6, keyPasses: 28, dribbles: 24, tackles: 34, interceptions: 24, passAccuracy: 82, shots: 10, shotsOnTarget: 3 },
  },
  {
    id: 'leo-chu',
    name: 'Léo Chú',
    teamId: 'seattle-sounders',
    position: 'RW',
    nationality: 'Brazilian',
    age: 24,
    guaranteedComp: 250_000,
    budgetCharge: 250_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 18, gamesStarted: 10, minutesPlayed: 840, goals: 3, assists: 2, xG: 2.8, xA: 1.8, keyPasses: 26, dribbles: 44, tackles: 8, interceptions: 6, passAccuracy: 74, shots: 26, shotsOnTarget: 11 },
  },

  // ─── ATLANTA UNITED ──────────────────────────────────────────────
  {
    id: 'giakoumakis',
    name: 'Giorgos Giakoumakis',
    teamId: 'atlanta-united',
    position: 'ST',
    nationality: 'Greek',
    age: 29,
    guaranteedComp: 3_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 18, assists: 4, xG: 16.2, xA: 3.6, keyPasses: 28, dribbles: 22, tackles: 6, interceptions: 4, passAccuracy: 70, shots: 96, shotsOnTarget: 46 },
  },
  {
    id: 'xande-silva',
    name: 'Xande Silva',
    teamId: 'atlanta-united',
    position: 'LW',
    nationality: 'Portuguese',
    age: 25,
    guaranteedComp: 2_000_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2240, goals: 8, assists: 9, xG: 7.2, xA: 8.1, keyPasses: 58, dribbles: 62, tackles: 14, interceptions: 10, passAccuracy: 78, shots: 52, shotsOnTarget: 24 },
  },
  {
    id: 'mosquera',
    name: 'Edwin Mosquera',
    teamId: 'atlanta-united',
    position: 'RW',
    nationality: 'Colombian',
    age: 22,
    guaranteedComp: 1_800_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 26, minutesPlayed: 2180, goals: 7, assists: 6, xG: 6.2, xA: 5.4, keyPasses: 48, dribbles: 72, tackles: 16, interceptions: 12, passAccuracy: 76, shots: 58, shotsOnTarget: 26 },
  },
  {
    id: 'brad-guzan',
    name: 'Brad Guzan',
    teamId: 'atlanta-united',
    position: 'GK',
    nationality: 'American',
    age: 39,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 30, minutesPlayed: 2700, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 66, shots: 0, shotsOnTarget: 0 },
  },
  {
    id: 'brooks-lennon',
    name: 'Brooks Lennon',
    teamId: 'atlanta-united',
    position: 'RB',
    nationality: 'American',
    age: 27,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 2, assists: 5, xG: 1.6, xA: 4.2, keyPasses: 28, dribbles: 18, tackles: 44, interceptions: 32, passAccuracy: 82, shots: 10, shotsOnTarget: 4 },
  },
  {
    id: 'caleb-wiley',
    name: 'Caleb Wiley',
    teamId: 'atlanta-united',
    position: 'LB',
    nationality: 'American',
    age: 19,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 22, minutesPlayed: 1880, goals: 1, assists: 3, xG: 0.7, xA: 2.4, keyPasses: 22, dribbles: 18, tackles: 32, interceptions: 20, passAccuracy: 80, shots: 5, shotsOnTarget: 2 },
  },
  {
    id: 'gregersen',
    name: 'Stian Gregersen',
    teamId: 'atlanta-united',
    position: 'CB',
    nationality: 'Norwegian',
    age: 29,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2280, goals: 2, assists: 1, xG: 1.4, xA: 0.8, keyPasses: 12, dribbles: 4, tackles: 50, interceptions: 42, passAccuracy: 85, shots: 7, shotsOnTarget: 3 },
  },
  {
    id: 'matt-hedges',
    name: 'Matt Hedges',
    teamId: 'atlanta-united',
    position: 'CB',
    nationality: 'American',
    age: 33,
    guaranteedComp: 400_000,
    budgetCharge: 400_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 20, minutesPlayed: 1740, goals: 1, assists: 1, xG: 0.8, xA: 0.8, keyPasses: 10, dribbles: 3, tackles: 44, interceptions: 36, passAccuracy: 84, shots: 5, shotsOnTarget: 2 },
  },
  {
    id: 'santiago-sosa',
    name: 'Santiago Sosa',
    teamId: 'atlanta-united',
    position: 'CDM',
    nationality: 'Argentinian',
    age: 25,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 24, minutesPlayed: 2080, goals: 1, assists: 2, xG: 0.8, xA: 1.8, keyPasses: 34, dribbles: 16, tackles: 68, interceptions: 52, passAccuracy: 87, shots: 12, shotsOnTarget: 4 },
  },
  {
    id: 'muyumba',
    name: 'Tristan Muyumba',
    teamId: 'atlanta-united',
    position: 'CM',
    nationality: 'Belgian',
    age: 21,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 14, minutesPlayed: 1180, goals: 2, assists: 3, xG: 1.8, xA: 2.6, keyPasses: 36, dribbles: 28, tackles: 32, interceptions: 22, passAccuracy: 82, shots: 16, shotsOnTarget: 6 },
  },
  {
    id: 'derrick-williams',
    name: 'Derrick Williams',
    teamId: 'atlanta-united',
    position: 'CB',
    nationality: 'Irish',
    age: 31,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 16, minutesPlayed: 1380, goals: 0, assists: 0, xG: 0.4, xA: 0.3, keyPasses: 8, dribbles: 2, tackles: 38, interceptions: 30, passAccuracy: 83, shots: 3, shotsOnTarget: 1 },
  },

  // ─── FC CINCINNATI ──────────────────────────────────────────────
  {
    id: 'acosta',
    name: 'Luciano Acosta',
    teamId: 'fc-cincinnati',
    position: 'CAM',
    nationality: 'Argentinian',
    age: 29,
    guaranteedComp: 4_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 32, gamesStarted: 30, minutesPlayed: 2640, goals: 7, assists: 16, xG: 6.4, xA: 14.2, keyPasses: 106, dribbles: 72, tackles: 22, interceptions: 14, passAccuracy: 87, shots: 42, shotsOnTarget: 18 },
  },
  {
    id: 'vasquez',
    name: 'Brandon Vásquez',
    teamId: 'fc-cincinnati',
    position: 'ST',
    nationality: 'Mexican-American',
    age: 25,
    guaranteedComp: 2_800_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 16, assists: 5, xG: 13.8, xA: 4.2, keyPasses: 26, dribbles: 28, tackles: 6, interceptions: 4, passAccuracy: 71, shots: 84, shotsOnTarget: 38 },
  },
  {
    id: 'barreal',
    name: 'Álvaro Barreal',
    teamId: 'fc-cincinnati',
    position: 'LW',
    nationality: 'Argentinian',
    age: 23,
    guaranteedComp: 2_100_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 24, minutesPlayed: 2080, goals: 6, assists: 8, xG: 5.4, xA: 7.2, keyPasses: 58, dribbles: 68, tackles: 18, interceptions: 14, passAccuracy: 77, shots: 52, shotsOnTarget: 22 },
  },
  {
    id: 'celentano',
    name: 'Roman Celentano',
    teamId: 'fc-cincinnati',
    position: 'GK',
    nationality: 'American',
    age: 23,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 34, gamesStarted: 34, minutesPlayed: 3060, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 68, shots: 0, shotsOnTarget: 0 },
  },
  {
    id: 'andrew-gutman',
    name: 'Andrew Gutman',
    teamId: 'fc-cincinnati',
    position: 'LB',
    nationality: 'American',
    age: 27,
    guaranteedComp: 350_000,
    budgetCharge: 350_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 24, minutesPlayed: 2080, goals: 1, assists: 3, xG: 0.7, xA: 2.4, keyPasses: 22, dribbles: 12, tackles: 38, interceptions: 24, passAccuracy: 81, shots: 6, shotsOnTarget: 2 },
  },
  {
    id: 'nwobodo',
    name: 'Obinna Nwobodo',
    teamId: 'fc-cincinnati',
    position: 'CDM',
    nationality: 'Nigerian',
    age: 24,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 2, assists: 3, xG: 1.6, xA: 2.4, keyPasses: 36, dribbles: 18, tackles: 72, interceptions: 56, passAccuracy: 86, shots: 14, shotsOnTarget: 5 },
  },
  {
    id: 'hagglund',
    name: 'Nick Hagglund',
    teamId: 'fc-cincinnati',
    position: 'CB',
    nationality: 'American',
    age: 30,
    guaranteedComp: 350_000,
    budgetCharge: 350_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2280, goals: 2, assists: 1, xG: 1.4, xA: 0.8, keyPasses: 12, dribbles: 4, tackles: 48, interceptions: 40, passAccuracy: 84, shots: 6, shotsOnTarget: 2 },
  },
  {
    id: 'valenzuela',
    name: 'Gerardo Valenzuela',
    teamId: 'fc-cincinnati',
    position: 'CM',
    nationality: 'Chilean',
    age: 22,
    guaranteedComp: 400_000,
    budgetCharge: 400_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 18, minutesPlayed: 1560, goals: 3, assists: 4, xG: 2.6, xA: 3.4, keyPasses: 44, dribbles: 32, tackles: 34, interceptions: 22, passAccuracy: 82, shots: 22, shotsOnTarget: 9 },
  },
  {
    id: 'miazga',
    name: 'Matt Miazga',
    teamId: 'fc-cincinnati',
    position: 'CB',
    nationality: 'American',
    age: 28,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 22, minutesPlayed: 1920, goals: 1, assists: 1, xG: 0.8, xA: 0.8, keyPasses: 10, dribbles: 3, tackles: 46, interceptions: 38, passAccuracy: 85, shots: 5, shotsOnTarget: 2 },
  },
  {
    id: 'yuya-kubo',
    name: 'Yuya Kubo',
    teamId: 'fc-cincinnati',
    position: 'RM',
    nationality: 'Japanese',
    age: 31,
    guaranteedComp: 1_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 20, minutesPlayed: 1720, goals: 5, assists: 6, xG: 4.4, xA: 5.2, keyPasses: 46, dribbles: 38, tackles: 16, interceptions: 12, passAccuracy: 80, shots: 36, shotsOnTarget: 15 },
  },
  {
    id: 'dejuan-jones',
    name: 'DeJuan Jones',
    teamId: 'fc-cincinnati',
    position: 'LB',
    nationality: 'American',
    age: 26,
    guaranteedComp: 400_000,
    budgetCharge: 400_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 18, minutesPlayed: 1560, goals: 0, assists: 3, xG: 0.3, xA: 2.4, keyPasses: 20, dribbles: 10, tackles: 36, interceptions: 24, passAccuracy: 80, shots: 4, shotsOnTarget: 1 },
  },

  // ─── COLUMBUS CREW ──────────────────────────────────────────────
  {
    id: 'cucho',
    name: 'Cucho Hernández',
    teamId: 'columbus-crew',
    position: 'ST',
    nationality: 'Colombian',
    age: 25,
    guaranteedComp: 4_500_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 14, assists: 8, xG: 12.4, xA: 7.2, keyPasses: 38, dribbles: 56, tackles: 10, interceptions: 8, passAccuracy: 72, shots: 82, shotsOnTarget: 38 },
  },
  {
    id: 'diego-rossi',
    name: 'Diego Rossi',
    teamId: 'columbus-crew',
    position: 'LW',
    nationality: 'Uruguayan',
    age: 24,
    guaranteedComp: 3_000_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2240, goals: 12, assists: 7, xG: 10.8, xA: 6.4, keyPasses: 56, dribbles: 74, tackles: 16, interceptions: 12, passAccuracy: 78, shots: 76, shotsOnTarget: 34 },
  },
  {
    id: 'zelarayan',
    name: 'Lucas Zelarayán',
    teamId: 'columbus-crew',
    position: 'CAM',
    nationality: 'Argentinian',
    age: 31,
    guaranteedComp: 2_100_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 22, minutesPlayed: 1880, goals: 5, assists: 10, xG: 4.6, xA: 9.2, keyPasses: 82, dribbles: 44, tackles: 18, interceptions: 12, passAccuracy: 84, shots: 34, shotsOnTarget: 14 },
  },
  {
    id: 'patrick-schulte',
    name: 'Patrick Schulte',
    teamId: 'columbus-crew',
    position: 'GK',
    nationality: 'American',
    age: 23,
    guaranteedComp: 400_000,
    budgetCharge: 400_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 34, gamesStarted: 34, minutesPlayed: 3060, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 70, shots: 0, shotsOnTarget: 0 },
  },
  {
    id: 'steven-moreira',
    name: 'Steven Moreira',
    teamId: 'columbus-crew',
    position: 'RB',
    nationality: 'American',
    age: 28,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 2, assists: 4, xG: 1.6, xA: 3.2, keyPasses: 26, dribbles: 14, tackles: 44, interceptions: 32, passAccuracy: 83, shots: 8, shotsOnTarget: 3 },
  },
  {
    id: 'aidan-morris',
    name: 'Aidan Morris',
    teamId: 'columbus-crew',
    position: 'CM',
    nationality: 'American',
    age: 22,
    guaranteedComp: 1_000_000,
    budgetCharge: 1_000_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 3, assists: 5, xG: 2.8, xA: 4.4, keyPasses: 54, dribbles: 32, tackles: 52, interceptions: 38, passAccuracy: 86, shots: 26, shotsOnTarget: 10 },
  },
  {
    id: 'mensah',
    name: 'Jonathan Mensah',
    teamId: 'columbus-crew',
    position: 'CB',
    nationality: 'Ghanaian',
    age: 33,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 22, minutesPlayed: 1920, goals: 1, assists: 0, xG: 0.8, xA: 0.3, keyPasses: 10, dribbles: 3, tackles: 44, interceptions: 36, passAccuracy: 84, shots: 4, shotsOnTarget: 1 },
  },
  {
    id: 'rudy-camacho',
    name: 'Rudy Camacho',
    teamId: 'columbus-crew',
    position: 'CB',
    nationality: 'French',
    age: 35,
    guaranteedComp: 350_000,
    budgetCharge: 350_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 18, minutesPlayed: 1560, goals: 1, assists: 1, xG: 0.7, xA: 0.8, keyPasses: 10, dribbles: 2, tackles: 38, interceptions: 32, passAccuracy: 83, shots: 4, shotsOnTarget: 2 },
  },
  {
    id: 'yaw-yeboah',
    name: 'Yaw Yeboah',
    teamId: 'columbus-crew',
    position: 'RW',
    nationality: 'Ghanaian',
    age: 26,
    guaranteedComp: 1_200_000,
    budgetCharge: 1_200_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 22, minutesPlayed: 1920, goals: 6, assists: 4, xG: 5.4, xA: 3.6, keyPasses: 42, dribbles: 62, tackles: 14, interceptions: 10, passAccuracy: 74, shots: 52, shotsOnTarget: 22 },
  },
  {
    id: 'degenek',
    name: 'Miloš Degenek',
    teamId: 'columbus-crew',
    position: 'RB',
    nationality: 'Australian/Serbian',
    age: 28,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 22, minutesPlayed: 1920, goals: 1, assists: 3, xG: 0.8, xA: 2.4, keyPasses: 22, dribbles: 10, tackles: 40, interceptions: 30, passAccuracy: 82, shots: 6, shotsOnTarget: 2 },
  },
  {
    id: 'alex-matan',
    name: 'Alex Matan',
    teamId: 'columbus-crew',
    position: 'LM',
    nationality: 'American',
    age: 23,
    guaranteedComp: 350_000,
    budgetCharge: 350_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 12, minutesPlayed: 1020, goals: 3, assists: 2, xG: 2.6, xA: 1.8, keyPasses: 28, dribbles: 36, tackles: 10, interceptions: 8, passAccuracy: 74, shots: 24, shotsOnTarget: 10 },
  },
  {
    id: 'jacen-russell-rowe',
    name: 'Jacen Russell-Rowe',
    teamId: 'columbus-crew',
    position: 'ST',
    nationality: 'Canadian',
    age: 21,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 12, minutesPlayed: 1020, goals: 5, assists: 2, xG: 4.4, xA: 1.8, keyPasses: 16, dribbles: 18, tackles: 4, interceptions: 3, passAccuracy: 68, shots: 34, shotsOnTarget: 15 },
  },

  // ─── PORTLAND TIMBERS ────────────────────────────────────────────
  {
    id: 'evander',
    name: 'Evander',
    teamId: 'portland-timbers',
    position: 'CAM',
    nationality: 'Brazilian',
    age: 26,
    guaranteedComp: 3_500_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 32, gamesStarted: 30, minutesPlayed: 2640, goals: 9, assists: 14, xG: 8.2, xA: 12.4, keyPasses: 92, dribbles: 66, tackles: 24, interceptions: 16, passAccuracy: 85, shots: 58, shotsOnTarget: 24 },
  },
  {
    id: 'santiago-moreno',
    name: 'Santiago Moreno',
    teamId: 'portland-timbers',
    position: 'RW',
    nationality: 'Colombian',
    age: 23,
    guaranteedComp: 2_400_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: true,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2440, goals: 10, assists: 7, xG: 9.2, xA: 6.4, keyPasses: 52, dribbles: 78, tackles: 18, interceptions: 12, passAccuracy: 76, shots: 68, shotsOnTarget: 30 },
  },
  {
    id: 'dairon-asprilla',
    name: 'Dairon Asprilla',
    teamId: 'portland-timbers',
    position: 'LW',
    nationality: 'Colombian',
    age: 31,
    guaranteedComp: 1_200_000,
    budgetCharge: 683_750,
    isDesignatedPlayer: false,
    isTAM: true,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 22, minutesPlayed: 1880, goals: 6, assists: 4, xG: 5.4, xA: 3.6, keyPasses: 44, dribbles: 56, tackles: 14, interceptions: 10, passAccuracy: 75, shots: 48, shotsOnTarget: 20 },
  },
  {
    id: 'niezgoda',
    name: 'Jarosław Niezgoda',
    teamId: 'portland-timbers',
    position: 'ST',
    nationality: 'Polish',
    age: 28,
    guaranteedComp: 750_000,
    budgetCharge: 750_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 16, minutesPlayed: 1380, goals: 8, assists: 2, xG: 7.2, xA: 1.8, keyPasses: 18, dribbles: 14, tackles: 4, interceptions: 3, passAccuracy: 68, shots: 52, shotsOnTarget: 24 },
  },
  {
    id: 'diego-chara',
    name: 'Diego Chará',
    teamId: 'portland-timbers',
    position: 'CDM',
    nationality: 'Colombian',
    age: 36,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 24, minutesPlayed: 2080, goals: 1, assists: 2, xG: 0.8, xA: 1.6, keyPasses: 28, dribbles: 14, tackles: 72, interceptions: 58, passAccuracy: 85, shots: 10, shotsOnTarget: 4 },
  },
  {
    id: 'paredes',
    name: 'Cristhian Paredes',
    teamId: 'portland-timbers',
    position: 'CDM',
    nationality: 'Paraguayan',
    age: 25,
    guaranteedComp: 400_000,
    budgetCharge: 400_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 22, minutesPlayed: 1880, goals: 2, assists: 3, xG: 1.6, xA: 2.4, keyPasses: 32, dribbles: 18, tackles: 58, interceptions: 44, passAccuracy: 84, shots: 14, shotsOnTarget: 5 },
  },
  {
    id: 'kamal-miller',
    name: 'Kamal Miller',
    teamId: 'portland-timbers',
    position: 'CB',
    nationality: 'Canadian',
    age: 26,
    guaranteedComp: 700_000,
    budgetCharge: 700_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 30, gamesStarted: 28, minutesPlayed: 2460, goals: 2, assists: 1, xG: 1.4, xA: 0.8, keyPasses: 12, dribbles: 4, tackles: 52, interceptions: 44, passAccuracy: 85, shots: 6, shotsOnTarget: 2 },
  },
  {
    id: 'araujo',
    name: 'Miguel Araujo',
    teamId: 'portland-timbers',
    position: 'CB',
    nationality: 'Peruvian',
    age: 26,
    guaranteedComp: 600_000,
    budgetCharge: 600_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 28, gamesStarted: 26, minutesPlayed: 2280, goals: 1, assists: 1, xG: 0.8, xA: 0.8, keyPasses: 10, dribbles: 3, tackles: 50, interceptions: 42, passAccuracy: 84, shots: 5, shotsOnTarget: 2 },
  },
  {
    id: 'eryk-williamson',
    name: 'Eryk Williamson',
    teamId: 'portland-timbers',
    position: 'CM',
    nationality: 'American',
    age: 27,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 26, gamesStarted: 20, minutesPlayed: 1740, goals: 2, assists: 4, xG: 1.8, xA: 3.4, keyPasses: 44, dribbles: 26, tackles: 36, interceptions: 24, passAccuracy: 83, shots: 18, shotsOnTarget: 7 },
  },
  {
    id: 'david-ayala',
    name: 'David Ayala',
    teamId: 'portland-timbers',
    position: 'CM',
    nationality: 'American',
    age: 24,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 20, gamesStarted: 12, minutesPlayed: 1020, goals: 1, assists: 2, xG: 0.9, xA: 1.8, keyPasses: 28, dribbles: 18, tackles: 28, interceptions: 18, passAccuracy: 81, shots: 10, shotsOnTarget: 4 },
  },
  {
    id: 'claudio-bravo-por',
    name: 'Claudio Bravo',
    teamId: 'portland-timbers',
    position: 'CM',
    nationality: 'Chilean',
    age: 27,
    guaranteedComp: 500_000,
    budgetCharge: 500_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 24, gamesStarted: 18, minutesPlayed: 1560, goals: 2, assists: 3, xG: 1.8, xA: 2.6, keyPasses: 36, dribbles: 22, tackles: 34, interceptions: 22, passAccuracy: 83, shots: 16, shotsOnTarget: 6 },
  },
  {
    id: 'zac-mcgraw',
    name: 'Zac McGraw',
    teamId: 'portland-timbers',
    position: 'RB',
    nationality: 'American',
    age: 24,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 22, gamesStarted: 16, minutesPlayed: 1380, goals: 0, assists: 2, xG: 0.3, xA: 1.6, keyPasses: 16, dribbles: 8, tackles: 30, interceptions: 20, passAccuracy: 80, shots: 3, shotsOnTarget: 1 },
  },
  {
    id: 'jeff-attinella',
    name: 'Jeff Attinella',
    teamId: 'portland-timbers',
    position: 'GK',
    nationality: 'American',
    age: 36,
    guaranteedComp: 300_000,
    budgetCharge: 300_000,
    isDesignatedPlayer: false,
    isTAM: false,
    season: '2024',
    stats: { gamesPlayed: 34, gamesStarted: 34, minutesPlayed: 3060, goals: 0, assists: 0, xG: 0, xA: 0, keyPasses: 0, dribbles: 0, tackles: 0, interceptions: 0, passAccuracy: 67, shots: 0, shotsOnTarget: 0 },
  },
];

export function getTeamPlayers(teamId: string): MLSPlayer[] {
  return MLS_PLAYERS.filter(p => p.teamId === teamId);
}

export function getTeamById(teamId: string): MLSTeam | undefined {
  return MLS_TEAMS.find(t => t.id === teamId);
}
